CREATE TABLE EMPLOYEE
(NAME VARCHAR(30) NOT NULL,
EMPLOYEEID CHAR(9) NOT NULL,
ADDRESS VARCHAR(30),
PHONE CHAR(9),
PRIMARY KEY (EMPLOYEEID));

CREATE TABLE HOURLY
(EMPLOYEEID CHAR(9) NOT NULL,
PRIMARY KEY (EMPLOYEEID));

CREATE TABLE STORE
(STORENO CHAR(10) NOT NULL,
SADDRESS VARCHAR(30),
SPHONE CHAR(9),
PRIMARY KEY (STORENO));

CREATE TABLE FULL_TIME
(EMPLOYEEID CHAR(9) NOT NULL,
SALARY INTEGER,
STORENO CHAR(10) NOT NULL,
CONSTRAINT fk_FULLTIMESTORENO
FOREIGN KEY (STORENO) REFERENCES STORE(STORENO)
ON DELETE CASCADE,
CONSTRAINT fk_FULLTIMEEMPLOYEE
FOREIGN KEY (EMPLOYEEID) REFERENCES EMPLOYEE(EMPLOYEEID)
ON DELETE CASCADE);
             
CREATE TABLE HWORKS
(EMPLOYEEID CHAR(9) NOT NULL,
RATE INTEGER,
HOURS INTEGER,
STORENO CHAR(10) NOT NULL,
CONSTRAINT fk_HWORKSSTORENO
FOREIGN KEY (STORENO) REFERENCES STORE(STORENO)
ON DELETE CASCADE,
CONSTRAINT fk_HOURLYEMPLOYEE
FOREIGN KEY (EMPLOYEEID) REFERENCES EMPLOYEE(EMPLOYEEID)
ON DELETE CASCADE);

CREATE TABLE MOVIE
(OBJECTID CHAR(9) NOT NULL,
TITLE VARCHAR(30),
DIRECTOR VARCHAR(30),
PRODUCER VARCHAR(30),
ACTOR1 VARCHAR(30),
ACTOR2 VARCHAR(30),
CATEGORY VARCHAR(30),
PRIMARY KEY (OBJECTID));
              
CREATE TABLE PLAYER
(OBJECTID CHAR(9) NOT NULL,
MODEL VARCHAR(15),
BRAND VARCHAR(15),
PLAYERFEATURE VARCHAR(15),
PRIMARY KEY (OBJECTID));
 
CREATE TABLE STORE_OBJECT
(OBJECTID CHAR(9) NOT NULL,
DAILYCHARGE INT,
COPYNO CHAR(9) NOT NULL,
PRIMARY KEY (OBJECTID));

CREATE TABLE COPY
(COPYNO CHAR(9) NOT NULL,
TYPE VARCHAR(10),
STAT VARCHAR(10),
OBJECTID CHAR(9) NOT NULL,
PRIMARY KEY (COPYNO),
CONSTRAINT fk_COPYOBJECTID
FOREIGN KEY (OBJECTID) 
REFERENCES MOVIE(OBJECTID)
ON DELETE CASCADE);

ALTER TABLE STORE_OBJECT
ADD CONSTRAINT fk_SOCOPY
FOREIGN KEY (COPYNO) REFERENCES COPY(COPYNO);
             
CREATE TABLE PLAYER_DEVICE
(COPYNO CHAR(9) NOT NULL,
STORENO CHAR(10) NOT NULL,
PRIMARY KEY (COPYNO),
FOREIGN KEY (STORENO) 
REFERENCES STORE(STORENO));
             
CREATE TABLE NO_ASSIGNED
(OBJECTID CHAR(9) NOT NULL,
STORENO CHAR(10) NOT NULL,
NODVD int,
NOBD int,
FOREIGN KEY (OBJECTID) 
REFERENCES MOVIE(OBJECTID),
FOREIGN KEY (STORENO) 
REFERENCES STORE(STORENO));
             
CREATE TABLE MEMBER
(MEMBERID CHAR(9) NOT NULL,
ADDRESS CHAR(30),
MEMBERNAME CHAR(30),
PASSWORD CHAR(15),
BALANCE DECIMAL(10,2) NOT NULL DEFAULT '0',
PRIMARY KEY (MEMBERID));
                 
CREATE TABLE INVOICE_TRANSACTION
(TRANSACTION_ID int NOT NULL AUTO_INCREMENT,
STAMP DATETIME,
AMOUNT int,
TYPE VARCHAR(10),
STORENO CHAR(10),
COPYNO CHAR(9) NOT NULL,
MEMBERID CHAR(9) NOT NULL,
PRIMARY KEY (TRANSACTION_ID),
FOREIGN KEY (STORENO)
REFERENCES STORE(STORENO),
FOREIGN KEY (COPYNO)
REFERENCES COPY(COPYNO),
FOREIGN KEY (MEMBERID)
REFERENCES MEMBER(MEMBERID));

ALTER TABLE EMPLOYEE
ADD PASSWORD VARCHAR(15);

DROP TABLE HOURLY;

ALTER TABLE MOVIE
CHANGE COLUMN OBJECTID MOVIEID
CHAR(9);

ALTER TABLE PLAYER
CHANGE COLUMN OBJECTID PLAYERID
CHAR(9);

RENAME TABLE STORE_OBJECT to STORE_CHARGE;

ALTER TABLE STORE_CHARGE
CHANGE COLUMN OBJECTID CHARGEID
CHAR(9);

ALTER TABLE NO_ASSIGNED
CHANGE COLUMN OBJECTID MOVIEID
CHAR(9);

/*
Ended up creating a separate fk instead of replacing copyno
*/
ALTER TABLE PLAYER_DEVICE
ADD PLAYERID CHAR(9);


ALTER TABLE PLAYER_DEVICE
ADD CONSTRAINT fk_PLYR_DEVICE_CPY
FOREIGN KEY (PLAYERID) REFERENCES PLAYER(PLAYERID);

ALTER TABLE COPY
CHANGE COLUMN OBJECTID MOVIEID
CHAR(9);